name: Publish to npm

on:
  push:
      branches: [master]
  pull_request:
      branches: [ZiMing]

jobs:
  publish:
    name: Publish to npm registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to your Node.js version

      - name: Publish to npm registry
        env:
          NODE_AUTH_TOKEN: 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
        run: |
          echo "//registry.npmjs.org//:_authToken=\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" > .npmrc
          npm publish --registry https://registry.npmjs.org/
          sleep 5
          npm publish --registry https://registry.npmjs.org/
        # Make sure you have set up the NPM_AUTH_TOKEN secret in your GitHub repository settings.
